version: '3'

services:
    backend:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/backend
        environment:
            FLASK_ENV: development
            DATABASE_URL: postgres://database:5432
            APP_SETTINGS: config.ConfigDevelopment
            PGDATABASE: main
            PGUSER: root
            PGPASSWORD: toor
        depends_on:
            - database
    database:
        image: postgres:12.3-alpine
        volumes:
            - database-data:/var/lib/postgresql/data/
        env_file:
            - db_init.env
        ports:
            - 5432:5432
volumes:
    database-data:
